export const DELETE_COURSE = 'DELETE_COURSE';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const CREATE_COURSE = 'CREATE_COURSE';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const FETCH_COURSES = 'FETCH_COURSES';
export const COURSE_DELETED_SUCCESS = 'COURSE_DELETED_SUCCESS';
